#! /bin/bash

docker volume create postgresql-data
docker stop postgres
docker rm postgres
docker run -p 5432:5432 \
       -v postgresql-data:/var/lib/postgresql/data \
       -e POSTGRES_PASSWORD=postgres \
       --name postgres \
       -d postgres
